CREATE TABLE IF NOT EXISTS note
(
    ID       INT           NOT NULL AUTO_INCREMENT,
    TITLE    VARCHAR(255) NOT NULL CHECK ( CHAR_LENGTH(TITLE) >= 0 AND CHAR_LENGTH(TITLE) <= 255 ),
    CONTENT    VARCHAR(3000)    NOT NULL,
    PRIMARY KEY (ID)
);